name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
          version: 1.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu,wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-on-failure: "false"
      - uses: cargo-bins/cargo-binstall@main
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Update npm and verify npx
        run: |
          npm install -g npm@latest
          which npx || npm install -g npx
      - name: Install project dependencies
        run: npm install -D tailwindcss @tailwindcss/cli
      - name: Install CLI
        run: cargo binstall dioxus-cli -y --force --version 0.6
      - name: Build
        run: |
          dx build --verbose --trace --platform web --release
          npx @tailwindcss/cli -c tailwind/tailwind.config.js -i tailwind/input.css -o assets/tailwind.css
